package SensorSimulationLanguage.runtime.simulation;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class MarkovLaw extends IDataSource {
  private List<MarkovState> states;
  private String name;

  public MarkovLaw(String name) {
    states = new ArrayList<MarkovState>();
    this.name = name;
  }

  @Override
  public String getNext() {
    return states.get(0).getName();
  }

  public void addState(MarkovState state) {
    states.add(state);
  }

  public void assertCorrectConfiguration() {
    {
      Iterator<MarkovState> state_it = ListSequence.fromList(states).iterator();
      MarkovState state_var;
      while (state_it.hasNext()) {
        state_var = state_it.next();
        if (!(state_var.isValid()) || state_var.getTransitions().size() != states.size()) {
          throw new RuntimeException("Invalid configuration for markov law " + name + " : \n" + "\t - either state " + state_var.getName() + "'s transitions don't sum-up to 1.0\n" + "\t - or there is a missmatch between the number of states and the number of transitions");
        }
      }
    }
  }

  public List<MarkovState> getStates() {
    return states;
  }
}
